/opt/codex/runtimes/codex-primary-runtime/dependencies/python/bin/python3.12 -I -S -B - <<'PY'
import pathlib,os,json,stat,datetime,hashlib
root=pathlib.Path('/workspace/vm-u2-source-24cf-r01');run=pathlib.Path('/workspace/vm-u2-run-24cf-r01');pre=root/'pre-cwd';raw=(root/'evidence/linux-pre.stdout.json').read_bytes();data=json.loads(raw);sha=lambda b:hashlib.sha256(b).hexdigest()
assert data['comparisonWithPinnedC3Executable']['matches']
assert data['python']['platform']=='linux' and data['python']['version'].startswith('3.12.')
assert not data['startupSiteImported'] and not data['siteOrPkgPathPresent'] and not data['startupNonStdlibOrigins'] and not data['postProbeNonStdlibOrigins']
ancestors=[]
for p in [pathlib.Path('/'),*reversed(run.parents[:-1]),run]:
 row={'path':str(p),'lexists':os.path.lexists(p),'symlink':p.is_symlink(),'resolveStrictFalse':str(p.resolve(strict=False))}
 if os.path.lexists(p):st=p.lstat();row.update(ownerUid=st.st_uid,mode=oct(stat.S_IMODE(st.st_mode)),isDirectory=p.is_dir())
 ancestors.append(row)
canonical=run.resolve(strict=False);owned=[p for p in pathlib.Path('/workspace').iterdir() if p.name.startswith(('ags-','vm-')) or p.name=='agent-governance-suite'];overlap=[]
for p in sorted(owned,key=lambda p:p.name):
 rp=p.resolve(strict=False);overlap.append({'path':str(p),'resolved':str(rp),'overlap':canonical.is_relative_to(rp) or rp.is_relative_to(canonical)})
futureArgv=['/opt/codex/runtimes/codex-primary-runtime/dependencies/python/bin/python3.12','-I','-S','-B','-X','utf8',str(root/'packet/runner.py'),'--run-root',str(run),'--runner-sha256','d00cf8b8d901915d9f7141bbbaae4e674535e9756dd4b0598d95063f79250af3','--manifest-sha256','07add40aeaea69d60bc88c64f477818a780a039e92e85b7bdcbe435fbea75162','--timeout','300']
out={'scope':'U2_FUTURE_RUNROOT_RO_NO_EXECUTION_GO','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'path':str(run),'resolveStrictFalse':str(canonical),'lexists':os.path.lexists(run),'ancestorComponents':ancestors,'allAncestorNoSymlink':all(not x['symlink'] for x in ancestors),'uppercaseFMComponents':[x for x in canonical.parts if x.startswith('FM-')],'uriAmbiguousCharactersPresent':{label:char in str(canonical) for label,char in [('percent','%'),('fragment','#'),('query','?'),('NUL',chr(0))]},'sourceRootResolve':str(root.resolve()),'packetResolve':str((root/'packet').resolve()),'ownedNonOverlap':overlap,'allNonOverlap':not any(x['overlap'] for x in overlap),'parentAvailable':run.parent.is_dir(),'parentWritable':os.access(run.parent,os.W_OK),'preCwd':{'path':str(pre),'resolve':str(pre.resolve()),'isSymlink':pre.is_symlink(),'empty':not any(pre.iterdir())},'futureArgv':futureArgv,'futureArgvExecuted':False,'childContract':'runner owns child1/retry0, private HOME/TMP/cwd, timeout300 wait/reap; UNKNOWN preserved','externalJobs':'UNKNOWN; no new global reservations/process safety inquiry','priorUnreadableProcesses':7,'nativeCommandId':None,'runrootCreated':False,'runnerProductImportsLoadersTestsFixturesProbesGO':0,'sourcePreDecisions':'PENDING independent SOURCE/PRE plus exact future instruction','freshness':'Read-only snapshot; execution freshness not granted'}
p=root/'evidence/runroot-ro.json'
with p.open('x',encoding='utf-8',newline='\n') as f:json.dump(out,f,indent=2);f.write('\n')
os.chmod(p,0o600);b=p.read_bytes();stderr=(root/'evidence/linux-pre.stderr.txt').read_bytes()
print(json.dumps({'utc':out['utc'],'linuxPre':{'path':str(root/'evidence/linux-pre.stdout.json'),'bytes':len(raw),'sha256':sha(raw),'stderrBytes':len(stderr),'stderrSha256':sha(stderr),'python':data['python'],'selectedStdlibAndNativePins':data['selectedStdlibAndNativePins'],'loadedModuleFilePinCount':len(data['loadedModuleFilePins']),'startupModuleCount':data['startupModuleCount'],'startupSysPath':data['startupSysPath'],'startupSiteImported':data['startupSiteImported'],'siteOrPkgPathPresent':data['siteOrPkgPathPresent'],'startupNonStdlibOrigins':data['startupNonStdlibOrigins'],'postProbeNonStdlibOrigins':data['postProbeNonStdlibOrigins'],'sqliteSurfaceObservation':data['sqliteSurfaceObservation']},'runrootRo':{'path':str(p),'bytes':len(b),'sha256':sha(b),'lexists':out['lexists'],'actualResolve':out['resolveStrictFalse'],'allAncestorNoSymlink':out['allAncestorNoSymlink'],'uppercaseFMComponents':out['uppercaseFMComponents'],'uriAmbiguousCharactersPresent':out['uriAmbiguousCharactersPresent'],'allNonOverlap':out['allNonOverlap'],'parentAvailable':out['parentAvailable'],'parentWritable':out['parentWritable'],'preCwd':out['preCwd'],'runrootCreated':False}},indent=2))
PY
